# Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

load("//tools/bazel/dart:defs.bzl", "dart2wasm_test", "dart_analyze_test")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "dart_files",
    srcs = glob(["*.dart"]),
    visibility = ["//visibility:public"],
)

dart2wasm_test(
    name = "simd_test",
    main = "simd_test.dart",
)

dart_analyze_test(
    name = "simd_analyze",
    srcs = ["//sdk:lib/_internal/wasm/common/simd.dart"],
)
