# Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

load("//tools/bazel/dart:defs.bzl", "dart2wasm_benchmark")

package(default_visibility = ["//visibility:public"])

# TODO(beads: sdk-245): Wire benchmark performance result emitters to Bazel artifact outputs.
dart2wasm_benchmark(
    name = "skeletal_animation_simd_wasm",
    main = "dart/SkeletalAnimationSIMD.dart",
)
